markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Proud Zhu
url: http://proudzhu.github.io
description: A fantastic blog that is fantastic.
twitter: proudzhu
github: proudzhu
gravatar_url: https://s.gravatar.com/avatar/24ebe043625d24dc94add5cb2bc58f52?s=80
