permalink: /posts/:title
markdown: kramdown

include: ['_pages']

gems:
  - jekyll-sitemap

name: Proud Zhu
url: http://proudzhu.github.io
description: A fantastic blog that is fantastic.
twitter: proudzhu
